ALTER PUBLICATION supabase_realtime ADD TABLE public.salas;
ALTER TABLE public.salas REPLICA IDENTITY FULL;
ALTER TABLE public.estoque REPLICA IDENTITY FULL;
ALTER TABLE public.produtos REPLICA IDENTITY FULL;
ALTER TABLE public.solicitacoes REPLICA IDENTITY FULL;
ALTER TABLE public.emprestimos REPLICA IDENTITY FULL;
ALTER TABLE public.dividas REPLICA IDENTITY FULL;
ALTER TABLE public.movimentacoes REPLICA IDENTITY FULL;